### ISSUE TITLE
CKAN API : Upload url link instead of files

### ISSUE THREAD

**Issue by carbowizzy** [ckan/ckanapi#125] opened 2017-09-20 14:10 UTC
Hi,

I developed this API to upload to my CKAN instance which works fine. However , i had like to upload url link and not file but i dont seem to get it working.

`r = requests.post('http://mysite/api/action/resource_create',

			                      data={'package_id': package['id'],
			                            'name': resource_name,
			                            'description':description,
			                            'format': extension,
			                            'url': 'upload',  # Needed to pass validation
			                            },
			                      headers={'Authorization': APIKEY},
			                      files = {'upload': (filename, 'http://mysite/file.pdf' )})`

Please kindly help me figure it out. Thanks

**Comment by wardi** [comment] 2017-09-21 14:27
duplicate of https://github.com/ckan/ckan/issues/3820, and not related to this repo

**Closed by wardi** 2017-09-21 14:27 UTC
